server:
  port: 8080
dubbo:
  application:
    name: dubbo_privoder
  registry:
    address: zookeeper://192.168.142.77:2181
  protocol:
    port: 20880
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  type-aliases-package: liu.hope.entity
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml