server:
  port: 8081
dubbo:
  application:
    name: dubbo_consumer
  registry:
    address: zookeeper://192.168.142.77:2181
  consumer:
    check: false
spring:
  thymeleaf:
    cache: false
fdfs:
  so-timeout: 1000
  connect-timeout: 1000
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
  tracker-list: 192.168.142.88:22122
image:
  path: http://192.168.142.88/